rp.enable=true
rp.endpoint=https://bestq.best-quality.in
rp.project=verona
rp.api.key=sedf_v9rTy4TlSTOJtdz-sagTFuu8FEC7FCvo0RfdT4g4O_eMs3dHi5xKgRKwscNRRdr2
rp.launch=Verona Mobile Automation
rp.description=Verona mobile Appium/TestNG suite
rp.convertimage=true
rp.batch.size.logs=20
