browser_caps.device=DeviceId_125403149G142674
browser_caps.os_version=14.0
video.log=false
network.log=false
tnt.use.local.grid=true
tnt.local.grid.ip=https://bestq.best-quality.in/api/v1/appium/wd/hub
